### ISSUE TITLE
Suggestion: Benchmarking latest llama-2 based models

### ISSUE THREAD

**Issue by UranusSeven** [THUDM/AgentBench#1] opened 2023-08-08 02:50 UTC
The evaluation is really cool. However, the open-source models on the leaderboard are no longer up-to-date.

Open-source models based on llama-2 surpass their earlier generations by a significant margin. So it is worth trying [vicuna-13B-v1.5](https://huggingface.co/lmsys/vicuna-13b-v1.5), [wizardlm-13B-v1.2](WizardLM/WizardLM-13B-V1.2).

**Comment by sweellan** [comment] 2023-08-09 06:58
claude2 as well？

**Comment by Longin-Yu** [comment] 2023-08-09 14:25
Thanks for the likes and reminders! We will evaluate latest models recently and update results in this repo.

**Comment by Dampfinchen** [comment] 2023-08-13 19:03
I agree. I would also like to see some merged models. A very popular and good performing one currently is https://huggingface.co/Gryphe/MythoMax-L2-13b

**Comment by NoahBPeterson** [comment] 2023-08-15 17:35
The open source models appear to be evaluated via [FastChat](https://github.com/lm-sys/FastChat). Would it be better to work through them to get these new models added?

**Comment by zhc7** [comment] 2023-10-15 07:55
Hi, we've updated the result.

**Closed by zhc7** 2023-10-15 07:55 UTC
Labels: enhancement

**Comment by olivarb** [comment] 2023-10-16 01:01
@zhc7 Are the results in the paper/website correct or are the results in the image in the README correct? Would you be able to add smaller models such as phi-1/phi-1.5?

**Comment by zhc7** [comment] 2023-10-16 01:16
As described, we've updated some settings in the benchmark. The data shown in README is our newest result. If you prefer the older version, you can check out branch v0.1.

**Comment by NoahBPeterson** [comment] 2023-10-16 01:46
Hi @zhc7,

There are new LLMs released every month, so the answer to the question "Which LLMs should be benchmarked?" will change frequently.

**Comment by olivarb** [comment] 2023-10-24 03:03
@zhc7 Can we profile our own models to compare to the published v0.2 benchmarks or just the `db` and `os` (`code-grounded`) tasks?

**Comment by zhc7** [comment] 2023-10-24 07:36
@olivarb Hi, you can profile all the task. Please refer to https://github.com/THUDM/AgentBench#next-steps.

**Comment by olivarb** [comment] 2023-10-24 09:35
@zhc7 How would I reproduce the results for the table? The documentation seems to be for `dbbench-std` and `os-std`. Is it possible to provide clear steps to run for the entire suite such that we can replicate the results?

**Comment by zhc7** [comment] 2023-10-24 09:56
@olivarb Thank you for your suggestion. For now, you may refer to https://github.com/THUDM/AgentBench#next-steps for full result reproduction guide. We'll try to make this process clearer and simpler.

**Comment by olivarb** [comment] 2023-10-24 18:59
@zhc7 Is it possible to benchmark phi-1 and phi-1.5 as well? I would like to refer to benchmarks in paper but don't see the results for phi which makes it harder to compare with.
